#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/lib.sh

[[ -n "$DEBUG" ]] && set -x

if ! declare -f $1 > /dev/null; then
  _tabs
  if [[ $1 == 'help' && -n "$2" ]]; then
    type $2 || echo ${!2}
  else
    headline 1 variables
    (declare -p; bash -l -c "source /etc/profile;declare -p" ) | cut -c 12- | sort -t'=' -k1,1 | grep -v BASH | awk -F '=' -v counter=0 -v last= '{ if ($1 != last) { if (counter == 0) { printf ("%-20s%s\n", last, lastval); } last=$1; lastval=$2; counter=0} else { counter++;  }; } ' |  sed 's/^/\t\t/'

    headline 1 functions
    for i in $(declare -F | sed s/'declare -f//g' | sort); do
      echo $i | sed 's/^/\t\t/'
    done
  fi
  exit 1
fi
fn=$1
shift

$fn "$@"
