#!/bin/bash
time=${1:-7}
for i in $(find . -mtime -$time -type f -name \*.mp3  | awk -F / ' { print $2"/"$3 } ' | uniq ); do
  #echo $i
  start=$(date +%s)
  echo $i
  mpv --no-audio-display "$i/"*.mp3
  diff=$(( $(date +%s) - $start ))
  if [[ $diff -lt "1" ]]; then
    echo "Time listening was $diff sec. Exiting!"
    exit
  fi
done
