#!/bin/bash
#
# This is a mapping of 
#   /usr/include/X11/keysymdef.h and
#   http://man.openbsd.org/OpenBSD-current/man1/tmux.1#KEY_BINDINGS
#
TMP=/tmp/mpvonce
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MPVCONTROL=mpv-control
[[ -e $DIR/prefs.sh ]] && . $DIR/prefs.sh
[[ -e "$TMP" ]] || mkdir "$TMP"

if [[ -n "$HOST" && "$HOST" != "localhost" ]]; then
  timeout 5s ssh "$HOST" "$MPVCONTROL $1"
  exit 0
fi

key=$1

volume() {
  pactl list sinks short | grep RUNNING | cut -f 1 | while read source ; do
    docmd "pactl set-sink-volume $source $1"
  done
  exit
}

docmd() {
  echo -e $(date +%s) $(whoami) "$key->($control)\n\t$1" >> "$TMP"/keycode
  $1
}

if [[ $1 == 'd' ]]; then
  ( docmd "mpv-lib details" ) | xmessage -timeout 14 -file -
  exit
fi

[[ $1 == '9' ]] && volume -2000 
[[ $1 == '0' ]] && volume +2000

declare -A mapping=( [q]='quit' [up]='forward 60' [down]='back 60' [left]='back' [right]='forward' [p]='p ENTER' [return]='ENTER' [space]='pauseplay' [comma]='prev' [period]='next' [s]='s ENTER' [r]='r ENTER' )

[[ -z "$1" ]] && printf "%s\n" "${!mapping[@]}" "${mapping[@]}" | pr -2t && exit 
[[ ${mapping[$1]+_} ]] && control=${mapping[$1]} || control=$1
[[ "$control" =~ (.*60|forward|prev|quit|back|next|pauseplay) ]] && docmd "$DIR/ipc-do.js $control" && exit

docmd "tmux send-keys -t $(cat $TMP/tmux-name) $control"
