#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/lib.sh

[[ -n "$DEBUG" ]] && set -x

if ! declare -f $1 > /dev/null; then
  echo "Woops, $1 is not defined"
  for i in $(declare -F | sed s/'declare -f//g' | sort); do
    echo $i
  done
  exit 1
fi
fn=$1
shift
$fn "$@"
