#!/bin/bash
#
# This is a mapping of 
#
#   /usr/include/X11/keysymdef.h and
#   http://man.openbsd.org/OpenBSD-current/man1/tmux.1#KEY_BINDINGS
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
[[ -e $DIR/prefs.sh ]] && . $DIR/prefs.sh

amixer_prefix='amixer -D pulse sset Master'
amixer_step=4%
pactl_source=$(pactl list sinks | grep -B 1 RUNNING | grep -E "^S" | cut -d "#" -f 2 | tail -1)
#pactl_prefix='pactl set-sink-volume $(pactl list sinks | grep -C 4 MPOW | grep -E "^S" | cut -d "#" -f 2)'
pactl_prefix="pactl set-sink-volume $pactl_source"
pactl_step=2000

dbg() {
  echo $(date) "$*" >> /tmp/keycode
}
  
docmd() {
  if [[ -n "$cmd" ]]; then
    if [[ -n "$host" && "$host" != "localhost" ]]; then
      timeout 5s ssh $host $cmd
    else
      set -x
      $cmd
    fi
    exit
  fi
}

if [[ $1 == 'd' ]]; then
  tmp=$(mktemp)
  ssh $host "~/bin/mpv-details" > $tmp
  xmessage -timeout 14 -file $tmp
  rm $tmp
  exit
elif [[ $1 == '9' ]]; then
  cmd="$pactl_prefix -$pactl_step"  # && $amixer_prefix $amixer_step-"
elif [[ $1 == '0' ]]; then
  cmd="$pactl_prefix +$pactl_step"  # && $amixer_prefix $amixer_step+"
fi
docmd

declare -A mapping=( [q]='quit' [up]='forward 60' [down]='back 60' [left]='back' [right]='forward' [p]='p ENTER' [return]='ENTER' [space]='pauseplay' [comma]='prev' [period]='next' [s]='s ENTER' [r]='r ENTER' )
[[ -z "$1" ]] && printf "%s\n" "${!mapping[@]}" "${mapping[@]}" | pr -2t && exit 0
[[ ${mapping[$1]+_} ]] && control=${mapping[$1]} || control=$1

dbg "$1->($control)"

cmd="tmux send-keys -t mpv-once $control"
case $control in
  *60|forward|prev|quit|back|next|pauseplay)
    cmd="${cmdbase}ipc-do.js $control"
    ;;
esac
dbg "$cmd"
docmd 

