#!/bin/bash
#
# This is a mapping of 
#
#   /usr/include/X11/keysymdef.h and
#   http://man.openbsd.org/OpenBSD-current/man1/tmux.1#KEY_BINDINGS
#
[[ -e $HOME/.me-props ]] && . $HOME/.me-props

amixer_prefix='amixer -D pulse sset Master'
amixer_step=4%
pactl_prefix='pactl set-sink-volume $(pactl list sinks | grep -C 4 MPOW | grep -E "^S" | cut -d "#" -f 2)'
pactl_step=2000

if [[ $1 == 'd' ]]; then
  tmp=$(mktemp)
  ssh $host "~/bin/mpv-details" > $tmp
  xmessage -timeout 14 -file $tmp
  rm $tmp
  exit
elif [[ $1 == '9' ]]; then
  timeout 5s ssh $host "$pactl_prefix -$pactl_step;$amixer_prefix $amixer_step-"
  exit
elif [[ $1 == '0' ]]; then
  timeout 5s ssh $host "$pactl_prefix +$pactl_step;$amixer_prefix $amixer_step+"
  exit
fi

declare -A mapping=( [left]='back' [right]='forward' [p]='pu ENTER' [return]='ENTER' [space]='" "' [comma]='prev' [period]='next' [s]='s ENTER' [r]='r ENTER' )
[[ ${mapping[$1]+_} ]] && control=${mapping[$1]} || control=$1

# debugging
#echo $(date) "$1->($control)" >> /tmp/keycode
#

case $control in

  forward|prev|back|next)
    cmd="ipc-do.js $control"
    ;;

  *)
    cmd="tmux send-keys -t mpv-once $control"
    ;;
esac

if [[ -n "$cmd" ]]; then
  if [[ -n "$host" && "$host" != "localhost" ]]; then
    timeout 5s ssh $host $cmd
  else
    $cmd
  fi
fi
